import Dish from "../interfaces/dish";

export const kenyanDishes: Dish[] = [
  {
    DishID: 1,
    DishName: "Ugali na Sukuma Wiki",
    DishDescription: "Classic maize meal served with sautéed collard greens.",
    DishPrice: 120,
    Available: "YES",
    DishImage: "/aurum1.jpg",
  },
  {
    DishID: 2,
    DishName: "Nyama Choma",
    DishDescription: "Charcoal-grilled goat meat, served with kachumbari.",
    DishPrice: 450,
    Available: "NO",
    DishImage: "/aurum2.jpg",
  },
  {
    DishID: 3,
    DishName: "Mukimo",
    DishDescription: "Mashed potatoes, peas, and greens – a Kikuyu delicacy.",
    DishPrice: 200,
    Available: "YES",
    DishImage: "/aurum3.jpg",
  },
  {
    DishID: 4,
    DishName: "Chapati",
    DishDescription: "Soft, layered flatbread – perfect with stews.",
    DishPrice: 50,
    Available: "YES",
    DishImage: "/aurum4.jpg",
  },
  {
    DishID: 5,
    DishName: "Tilapia Fry",
    DishDescription: "Deep-fried fresh tilapia served with ugali and greens.",
    DishPrice: 600,
    Available: "YES",
    DishImage: "/aurum5.jpg",
  },
  {
    DishID: 6,
    DishName: "Matoke",
    DishDescription: "Stewed plantains with tomatoes, onions, and spices.",
    DishPrice: 180,
    Available: "YES",
    DishImage: "/aurum6.jpg",
  },
  {
    DishID: 7,
    DishName: "Githeri",
    DishDescription: "Traditional mix of maize and beans, slow-cooked.",
    DishPrice: 150,
    Available: "YES",
    DishImage: "/aurum7.jpg",
  },
  {
    DishID: 8,
    DishName: "Kachumbari",
    DishDescription: "Fresh tomato, onion, and chili salad.",
    DishPrice: 80,
    Available: "YES",
    DishImage: "/aurum8.jpg",
  },
  {
    DishID: 9,
    DishName: "Mutura",
    DishDescription: "Kenyan street-style sausage made with spiced meat and blood.",
    DishPrice: 100,
    Available: "NO",
    DishImage: "/aurum9.jpg",
  },
  {
    DishID: 10,
    DishName: "Pilau",
    DishDescription: "Fragrant spiced rice with beef and potatoes, coastal style.",
    DishPrice: 300,
    Available: "YES",
    DishImage: "/aurum10.jpg",
  },
  {
    DishID: 11,
    DishName: "Mandazi",
    DishDescription: "Lightly fried dough, slightly sweet – perfect for tea time.",
    DishPrice: 40,
    Available: "YES",
    DishImage: "/aurum1.jpg",
  },
  {
    DishID: 12,
    DishName: "Irio",
    DishDescription: "Green peas, corn, and mashed potatoes, Kikuyu-style.",
    DishPrice: 180,
    Available: "YES",
    DishImage: "/aurum2.jpg",
  },
  {
    DishID: 13,
    DishName: "Samosa",
    DishDescription: "Crispy triangles stuffed with spiced minced beef or vegetables.",
    DishPrice: 70,
    Available: "YES",
    DishImage: "/aurum3.jpg",
  },
  {
    DishID: 14,
    DishName: "Matumbo Stew",
    DishDescription: "Spiced tripe stew served with ugali or rice.",
    DishPrice: 250,
    Available: "NO",
    DishImage: "/aurum4.jpg",
  },
  {
    DishID: 15,
    DishName: "Maharagwe ya Nazi",
    DishDescription: "Kidney beans cooked in a creamy coconut sauce, coastal style.",
    DishPrice: 200,
    Available: "YES",
    DishImage: "/aurum5.jpg",
  },
  {
    DishID: 16,
    DishName: "Fish Curry",
    DishDescription: "Spicy coconut-based fish curry served with rice.",
    DishPrice: 500,
    Available: "YES",
    DishImage: "/aurum6.jpg",
  },
  {
    DishID: 17,
    DishName: "Bhajia",
    DishDescription: "Thinly sliced potatoes deep-fried in spiced gram flour batter.",
    DishPrice: 120,
    Available: "YES",
    DishImage: "/aurum7.jpg",
  },
  {
    DishID: 18,
    DishName: "Ndengu Stew",
    DishDescription: "Green gram stew, perfect with chapati or rice.",
    DishPrice: 180,
    Available: "YES",
    DishImage: "/aurum8.jpg",
  },
  {
    DishID: 19,
    DishName: "Chicken Biriyani",
    DishDescription: "Coastal-style chicken biryani with fragrant rice and spices.",
    DishPrice: 550,
    Available: "YES",
    DishImage: "/aurum9.jpg",
  },
  {
    DishID: 20,
    DishName: "Arrowroots (Nduma)",
    DishDescription: "Boiled arrowroots served with tea – a healthy breakfast option.",
    DishPrice: 100,
    Available: "YES",
    DishImage: "/aurum10.jpg",
  },
];
