import { paymentStatus, served } from "@/types/dishes";
import type Order from "@/interfaces/order";

const orders: Order[] = [
  {
    OrderID: 1,
    UnitID: 2,
    RegID: 5,
    DishID: 1,
    DishName: "Grilled Tilapia with Lemon Butter",
    DishPrice: 1200,
    Plates: 2,
    OrderPrice: 2400,
    OrderDescription: "Fresh tilapia fillet grilled to perfection, topped with lemon butter sauce.",
    OrderDate: "2025-08-31",
    OrderTime: "12:15",
    PaymentStatus: "Paid",
    Served: "YES",
    Image: '/aurum1.jpg',
  },
  {
    OrderID: 2,
    UnitID: 1,
    RegID: 8,
    DishID: 2,
    DishName: "Beef Sukuma with Ugali",
    DishPrice: 700,
    Plates: 3,
    OrderPrice: 2100,
    OrderDescription: "Tender beef stew with sukuma wiki served with a side of soft ugali.",
    OrderDate: "2025-08-31",
    OrderTime: "12:25",
    PaymentStatus: "Paid",
    Served: "NO",
    Image: '/aurum2.jpg',
  },
  {
    OrderID: 3,
    UnitID: 3,
    RegID: 2,
    DishID: 3,
    DishName: "Spaghetti Carbonara",
    DishPrice: 950,
    Plates: 1,
    OrderPrice: 950,
    OrderDescription: "Classic Italian pasta with creamy sauce, parmesan, and crispy bacon.",
    OrderDate: "2025-08-31",
    OrderTime: "12:40",
    PaymentStatus: "Paid",
    Served: "YES",
    Image: new File([], "/aurum3.jpg", { type: "image/jpeg" }),
  },
  {
    OrderID: 4,
    UnitID: 1,
    RegID: 12,
    DishID: 4,
    DishName: "Chicken Biryani",
    DishPrice: 1100,
    Plates: 2,
    OrderPrice: 2200,
    OrderDescription: "Spiced basmati rice layered with tender chicken and aromatic herbs.",
    OrderDate: "2025-08-31",
    OrderTime: "12:50",
    PaymentStatus: "Paid",
    Served: "NO",
    Image: new File([], "/aurum4.jpg", { type: "image/jpeg" }),
  },
  {
    OrderID: 5,
    UnitID: 2,
    RegID: 15,
    DishID: 5,
    DishName: "Vegetable Stir Fry with Noodles",
    DishPrice: 850,
    Plates: 1,
    OrderPrice: 850,
    OrderDescription: "Crisp vegetables sautéed with soy sauce and garlic served over noodles.",
    OrderDate: "2025-08-31",
    OrderTime: "13:00",
    PaymentStatus: "Paid",
    Served: "NO",
    Image: new File([], "/aurum5.jpg", { type: "image/jpeg" }),
  },
  {
    OrderID: 6,
    UnitID: 3,
    RegID: 3,
    DishID: 6,
    DishName: "Nyama Choma with Kachumbari",
    DishPrice: 1300,
    Plates: 2,
    OrderPrice: 2600,
    OrderDescription: "Charcoal-grilled goat meat served with fresh tomato and onion salad.",
    OrderDate: "2025-08-31",
    OrderTime: "13:15",
    PaymentStatus: "Paid",
    Served: "NO",
    Image: new File([], "/aurum6.jpg", { type: "image/jpeg" }),
  },
  {
    OrderID: 7,
    UnitID: 4,
    RegID: 9,
    DishID: 7,
    DishName: "Chicken Caesar Salad",
    DishPrice: 950,
    Plates: 1,
    OrderPrice: 950,
    OrderDescription: "Crisp lettuce, grilled chicken strips, parmesan, and Caesar dressing.",
    OrderDate: "2025-08-31",
    OrderTime: "13:30",
    PaymentStatus: "Not Paid",
    Served: "NO",
    Image: new File([], "/aurum7.jpg", { type: "image/jpeg" }),
  },
  {
    OrderID: 8,
    UnitID: 1,
    RegID: 7,
    DishID: 8,
    DishName: "Paneer Tikka Masala",
    DishPrice: 1000,
    Plates: 2,
    OrderPrice: 2000,
    OrderDescription: "Indian cottage cheese simmered in a spiced tomato-based curry sauce.",
    OrderDate: "2025-08-31",
    OrderTime: "13:45",
    PaymentStatus: "Paid",
    Served: "YES",
    Image: new File([], "/aurum8.jpg", { type: "image/jpeg" }),
  },
  {
    OrderID: 9,
    UnitID: 5,
    RegID: 4,
    DishID: 9,
    DishName: "Seafood Paella",
    DishPrice: 1500,
    Plates: 1,
    OrderPrice: 1500,
    OrderDescription: "Spanish rice dish with shrimp, mussels, and calamari in saffron broth.",
    OrderDate: "2025-08-31",
    OrderTime: "14:00",
    PaymentStatus: "Paid",
    Served: "NO",
    Image: new File([], "/aurum9.jpg", { type: "image/jpeg" }),
  },
  {
    OrderID: 10,
    UnitID: 2,
    RegID: 10,
    DishID: 10,
    DishName: "BBQ Ribs with Fries",
    DishPrice: 1400,
    Plates: 3,
    OrderPrice: 4200,
    OrderDescription: "Slow-cooked BBQ pork ribs served with crispy golden fries.",
    OrderDate: "2025-08-31",
    OrderTime: "14:20",
    PaymentStatus: "Not Paid",
    Served: "NO",
    Image: new File([], "/aurum10.jpg", { type: "image/jpeg" }),
  },
];

export default orders;
